services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-mvc

  php-mvc:
    container_name: php-mvc
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    container_name: php-mvc-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: